### ISSUE TITLE
Bareos 18 - Plugin not working

### ISSUE THREAD

**Issue by jvalters** [bareos/bareos-contrib#45]
Hello, 
1. I would like to say thank you for wonderful plugin.
2. This plugin works on Bareos 17.2
3. This plugin stops working on Bareos 18.X

Can you please take a look?
Would be also great if you would create a plugin for MongoDB backups since MongoDB is getting popular.

Thanks.

**Comment by joergsteffens** [comment]
This repository contains multiple plugins. Which plugin is not working anymore? With which version von Bareos 18.2. have you tested?

**Comment by joergsteffens** [comment]
No response. Closed.
