### ISSUE TITLE
bareos 19.

### ISSUE THREAD

**Issue by hellEVIL-13** [bareos/bareos-contrib#50]
Please help me bareos-fd crash

(150): filed/fd_plugins.cc:1836-2075 Instantiate plugin_ctx=801b70060 JobId=2075
Fatal Python error: PyEval_AcquireLock: current thread state is NULL

**Comment by arogge** [comment]
This is a problem in core, not in contrib.
Maybe ask on the mailing-list: https://groups.google.com/forum/?hl=de#!forum/bareos-users
