### ISSUE TITLE
Plugin bareos-fd-mysql not working after update to Bareos 20

### ISSUE THREAD

**Issue by elcomtik** [bareos/bareos-contrib#51]
Hi, I just recently updated Bareos to latest version 20, all components use the latest available packaged software

> 
bareos.x86_64                                20.0.0-1.el7               @bareos 
bareos-bconsole.x86_64                       20.0.0-1.el7               @bareos 
bareos-client.x86_64                         20.0.0-1.el7               @bareos 
bareos-common.x86_64                         20.0.0-1.el7               @bareos 
bareos-database-common.x86_64                20.0.0-1.el7               @bareos 
bareos-database-postgresql.x86_64            20.0.0-1.el7               @bareos 
bareos-database-tools.x86_64                 20.0.0-1.el7               @bareos 
bareos-director.x86_64                       20.0.0-1.el7               @bareos 
bareos-filedaemon.x86_64                     20.0.0-1.el7               @bareos 
bareos-filedaemon-percona-xtrabackup-python-plugin.x86_64
                                             20.0.0-1.el7               @bareos 
bareos-filedaemon-python-plugins-common.x86_64
                                             20.0.0-1.el7               @bareos 
bareos-filedaemon-python2-plugin.x86_64      20.0.0-1.el7               @bareos 
bareos-filedaemon-python3-plugin.x86_64      20.0.0-1.el7               @bareos 
bareos-storage.x86_64                        20.0.0-1.el7               @bareos 
bareos-tools.x86_64                          20.0.0-1.el7               @bareos 
bareos-webui.x86_64                          20.0.0-1.el7               @bareos 
bareos-contrib-filedaemon-python-plugin-mysql                  16.2.0.git.1535130545-8.3.el7                                                      @bareos-contrib

Job failed with following error
`bareos-fd JobId 61286: Fatal error: bareosfd: Traceback (most recent call last):
File "/usr/lib64/bareos/plugins/bareos-fd-mysql.py", line 9, in
from bareos_fd_consts import *
ImportError: No module named bareos_fd_consts`

Can you help me to fix this issue? thanks a lot.

**Comment by joergsteffens** [comment]
The repository https://github.com/bareos/bareos-contrib only contains user contributions to the Bareos project.
These are not supported by the Bareos project.
With Bareos 20 the Python plugin interface have been modernized. However, this requires that plugins must be adapted to it.
All plugins maintained in https://github.com/bareos/bareos have been adapted.

https://docs.bareos.org/TasksAndConcepts/Plugins.html#porting-existing-python-plugins gives background information about this and porting hints. Contributions to this are very welcome.

However, there is also a maintained version of a MySQL backup plugin: https://docs.bareos.org/TasksAndConcepts/Plugins.html#backup-mysql-xtrabackup

While more complex, it also offers incremental MySQL backups.

**Comment by elcomtik** [comment]
> https://docs.bareos.org/TasksAndConcepts/Plugins.html#porting-existing-python-plugins gives background information about this and porting hints. Contributions to this are very welcome.

Maybe someday I will look at it.

> However, there is also a maintained version of a MySQL backup plugin: https://docs.bareos.org/TasksAndConcepts/Plugins.html#backup-mysql-xtrabackup
> 
> While more complex, it also offers incremental MySQL backups.

I switched to this plugin however, there are use cases when simplicity matters

**Comment by joergsteffens** [comment]
I do agree. However, for now I'll close this issue.

**Comment by elcomtik** [comment]
I looked at changes needed to port this plugin to bareos 20, it seems pretty easy.

If I port it would there be any help to build packages and distribute them through contrib repository?

**Comment by joergsteffens** [comment]
Thank you for your contribution. About publishing of https://download.bareos.org/bareos/contrib/ I've to admit, that this repository is currently stalled. It is one of our TODOs to merge this github repository into the main bareos repository, making it easier

- to keep the contributions in sync with the core product
- build packages

**Comment by elcomtik** [comment]
OK, I agree with you. Merging makes sense to me, too. 

I'll wait for it. However, I guess it will not be sooner than with the release of Bareos 21.

**Comment by joergsteffens** [comment]
Package should be available at https://download.bareos.org/bareos/experimental/nightly/ before, but for a released version: yes.

**Comment by elcomtik** [comment]
Thank for the clarification, I'll look for nightly builds. 

Until then, I'll use distribute this plugin from Github sources through Bareos ansible role, which I'm currently developing.
