### ISSUE TITLE
MySQL Plugin and Python 3

### ISSUE THREAD

**Issue by Ryushin** [bareos/bareos-contrib#55]
I just upgraded my Bareos install to v20.  I've installed the latest mysql plugin.

I was getting these errors in BareosFdMySQLclass.py:
```
File "/usr/lib/bareos/plugins/BareosFdMySQLclass.py", line 202
    except Exception,msg:
                    ^
SyntaxError: invalid syntax
```
I changed the except statements a lines 202 and 223 to use "as" instead of a comma:  I.e.: except Exception as msg:

Line 208 had this error:
```print msg;
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(msg)?
```
I added the parentheses and it worked fine.

I'm working on trying to fix this error now:
```
26-Mar 08:37 wisp-fd JobId 19328: Fatal error: bareosfd: Traceback (most recent call last):
  File "/usr/lib/bareos/plugins/BareosFdWrapper.py", line 42, in start_backup_file
    return bareos_fd_plugin_object.start_backup_file(savepkt)
  File "/usr/lib/bareos/plugins/BareosFdMySQLclass.py", line 171, in start_backup_file
    savepkt.fname = "/_mysqlbackups_/" + db + ".sql"
TypeError: can only concatenate str (not "bytes") to str

26-Mar 08:37 wisp-fd JobId 19328: Fatal error: filed/fd_plugins.cc:2570 Command plugin: no fname in bareosCheckChanges packet.```

**Comment by joergsteffens** [comment]
Thank you for reporting this issue.

As you probably have noticed, the code has recently moved into the main repository at https://github.com/bareos/bareos/tree/master/contrib
We are working on getting this better integration, see
https://github.com/bareos/bareos/pull/766
and https://github.com/bareos/bareos/pull/768
I added a fix for the issues you reported to the second PR: https://github.com/bareos/bareos/pull/768/commits/60db5fbab94cc43a702b945fcf7f2efbfe1621d5

I hope this helps.
Anyhow, as this code now resides in another repository, I'll close this issue.
